# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-5-4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-5-4
pod "PGFramework"
  target 'Test-5-4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-5-4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
